export const gu = {
  "nav.home": "હોમ", "nav.scanner": "સ્કેમ સ્કેનર", "nav.childSafety": "બાળ સુરક્ષા", "nav.dashboard": "ડેશબોર્ડ", "nav.alerts": "ચેતવણીઓ", "nav.family": "પરિવાર", "nav.wellbeing": "સુખાકારી", "nav.womenSafety": "મહિલા સુરક્ષા", "nav.impact": "અસર", "nav.about": "અમારા વિશે", "nav.settings": "સેટિંગ્સ", "nav.login": "લૉગિન", "nav.signup": "સાઇન અપ", "nav.logout": "લૉગઆઉટ", "nav.emergency": "🆘 કટોકટી",
  "landing.hero.title": "ભારતનું AI રક્ષક", "landing.hero.titleHighlight": "ડિજિટલ સુરક્ષા", "landing.hero.subtitle": "બાળકો, પરિવારો અને વૃદ્ધોને સાયબર છેતરપિંડી, સ્કેમ અને ઓનલાઇન ધમકીઓથી રક્ષણ — AI દ્વારા, ભારત માટે બનાવેલ.", "landing.hero.cta": "તમારા પરિવારની સુરક્ષા શરૂ કરો", "landing.hero.ctaSecondary": "વધુ જાણો",
  "landing.features.title": "AI-સંચાલિત સુરક્ષા", "landing.features.subtitle": "દરેક ભારતીય પરિવાર માટે રિયલ-ટાઇમ ધમકી શોધ", "landing.features.scam.title": "સ્કેમ અને ફિશિંગ શોધ", "landing.features.scam.desc": "AI SMS, ઈમેલ, લિંક અને QR કોડનું વિશ્લેષણ કરે છે.", "landing.features.child.title": "બાળ સુરક્ષા AI", "landing.features.child.desc": "ઓનલાઇન ગ્રૂમિંગ, શિકારી વર્તન અને હાનિકારક સામગ્રી શોધે છે.", "landing.features.elderly.title": "વૃદ્ધ સુરક્ષા મોડ", "landing.features.elderly.desc": "એક-ટેપ 'શું આ સ્કેમ છે?' મોટા ટેક્સ્ટ, સ્પષ્ટ પરિણામો અને અવાજ ચેતવણીઓ સાથે.", "landing.features.women.title": "મહિલા સુરક્ષા", "landing.features.women.desc": "નકલી પ્રોફાઇલ, સેક્સટોર્શન અને બ્લેકમેલ શોધ.", "landing.features.dashboard.title": "વાલી ડેશબોર્ડ", "landing.features.dashboard.desc": "અવરોધિત ધમકીઓ, જોખમ સ્કોર અને પરિવાર સુરક્ષા વલણોનું વિઝ્યુઅલ ઓવરવ્યૂ.", "landing.features.privacy.title": "ગોપનીયતા-પ્રથમ AI", "landing.features.privacy.desc": "કાયમી સંદેશ સંગ્રહ નહીં. પારદર્શક AI સ્પષ્ટીકરણો. તમારો ડેટા તમારો.",
  "landing.impact.title": "ભારતને સુરક્ષિત બનાવવું", "landing.impact.threats": "ધમકીઓ અટકાવી", "landing.impact.scams": "સ્કેમ શોધ્યા", "landing.impact.children": "બાળકો સુરક્ષિત", "landing.impact.saved": "બચાવ્યા (₹)", "landing.modes.title": "બધા માટે બનાવેલ", "landing.modes.subtitle": "CyberShield તમારી જરૂરિયાતો અનુસાર અનુકૂળ થાય છે", "landing.cta.title": "આજે જ તમારા પરિવારની સુરક્ષા કરો", "landing.cta.subtitle": "AI-સંચાલિત ડિજિટલ સુરક્ષા વાપરતા હજારો ભારતીય પરિવારો સાથે જોડાઓ.", "landing.cta.button": "મફત શરૂ કરો",
  "auth.login.title": "પાછા સ્વાગત", "auth.login.subtitle": "તમારા CyberShield ખાતામાં સાઇન ઇન કરો", "auth.signup.title": "ખાતું બનાવો", "auth.signup.subtitle": "આજે જ તમારા પરિવારની સુરક્ષા શરૂ કરો", "auth.email": "ઈમેલ", "auth.password": "પાસવર્ડ", "auth.name": "પૂરું નામ", "auth.loginButton": "સાઇન ઇન", "auth.signupButton": "ખાતું બનાવો", "auth.noAccount": "ખાતું નથી?", "auth.hasAccount": "પહેલેથી ખાતું છે?", "auth.checkEmail": "ચકાસણી લિંક માટે તમારું ઈમેલ તપાસો.",
  "onboarding.title": "તમે CyberShield કેવી રીતે વાપરશો?", "onboarding.subtitle": "અમે તમારો અનુભવ કસ્ટમાઇઝ કરીશું", "onboarding.parent": "વાલી", "onboarding.parentDesc": "પરિવાર સુરક્ષા અને ધમકી દેખરેખ", "onboarding.child": "યુવા વપરાશકર્તા", "onboarding.childDesc": "સુરક્ષિત બ્રાઉઝિંગ અને સુખાકારી", "onboarding.elderly": "વરિષ્ઠ નાગરિક", "onboarding.elderlyDesc": "સરળ સ્કેમ શોધ", "onboarding.continue": "ચાલુ રાખો",
  "scanner.title": "સ્કેમ સ્કેનર", "scanner.subtitle": "AI વિશ્લેષણ માટે શંકાસ્પદ સંદેશ અથવા URL પેસ્ટ કરો", "scanner.textTab": "ટેક્સ્ટ સંદેશ", "scanner.urlTab": "URL / લિંક", "scanner.textPlaceholder": "શંકાસ્પદ SMS, WhatsApp સંદેશ, અથવા ઈમેલ ટેક્સ્ટ અહીં પેસ્ટ કરો...", "scanner.urlPlaceholder": "https://suspicious-link.com", "scanner.scanButton": "હવે સ્કેન કરો", "scanner.scanning": "વિશ્લેષણ થઈ રહ્યું છે...", "scanner.result.safe": "સુરક્ષિત", "scanner.result.suspicious": "શંકાસ્પદ", "scanner.result.dangerous": "ખતરનાક", "scanner.elderly.title": "શું આ સ્કેમ છે?", "scanner.elderly.subtitle": "નીચે સંદેશ પેસ્ટ કરો અને મોટું બટન દબાવો", "scanner.elderly.button": "હવે તપાસો",
  "dashboard.title": "ડેશબોર્ડ", "dashboard.threats": "ધમકીઓ અટકાવી", "dashboard.scams": "સ્કેમ શોધ્યા", "dashboard.riskScore": "પરિવાર જોખમ સ્કોર", "dashboard.recentAlerts": "તાજેતરની ચેતવણીઓ", "dashboard.scanHistory": "સ્કેન ઇતિહાસ", "dashboard.noData": "હજુ કોઈ ડેટા નથી. ઇનસાઇટ્સ જોવા સ્કેનિંગ શરૂ કરો.",
  "emergency.sos.title": "કટોકટી SOS", "emergency.sos.subtitle": "ચકાસાયેલ રાષ્ટ્રીય હેલ્પલાઇન અને કટોકટી સહાય માટે ત્વરિત પ્રવેશ", "emergency.sos.confirm": "તમે ખતરામાં છો?", "emergency.sos.yes": "હા, મને મદદ જોઈએ", "emergency.sos.no": "ના, હું સુરક્ષિત છું",
  "common.loading": "લોડ થઈ રહ્યું છે...", "common.error": "કંઈક ખોટું થયું", "common.darkMode": "ડાર્ક મોડ", "common.lightMode": "લાઇટ મોડ", "common.language": "ભાષા",
} as const;
