export const kn = {
  "nav.home": "ಮುಖಪುಟ", "nav.scanner": "ವಂಚನೆ ಸ್ಕ್ಯಾನರ್", "nav.childSafety": "ಮಕ್ಕಳ ಸುರಕ್ಷತೆ", "nav.dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", "nav.alerts": "ಎಚ್ಚರಿಕೆಗಳು", "nav.family": "ಕುಟುಂಬ", "nav.wellbeing": "ಯೋಗಕ್ಷೇಮ", "nav.womenSafety": "ಮಹಿಳಾ ಸುರಕ್ಷತೆ", "nav.impact": "ಪ್ರಭಾವ", "nav.about": "ನಮ್ಮ ಬಗ್ಗೆ", "nav.settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", "nav.login": "ಲಾಗಿನ್", "nav.signup": "ಸೈನ್ ಅಪ್", "nav.logout": "ಲಾಗ್‌ಔಟ್", "nav.emergency": "🆘 ತುರ್ತು",
  "landing.hero.title": "ಭಾರತದ AI ರಕ್ಷಕ", "landing.hero.titleHighlight": "ಡಿಜಿಟಲ್ ಸುರಕ್ಷತೆ", "landing.hero.subtitle": "ಮಕ್ಕಳು, ಕುಟುಂಬಗಳು & ಹಿರಿಯರನ್ನು ಸೈಬರ್ ವಂಚನೆ, ಸ್ಕ್ಯಾಮ್‌ಗಳು ಮತ್ತು ಆನ್‌ಲೈನ್ ಬೆದರಿಕೆಗಳಿಂದ ರಕ್ಷಿಸುವುದು — AI ಮೂಲಕ, ಭಾರತಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.", "landing.hero.cta": "ನಿಮ್ಮ ಕುಟುಂಬವನ್ನು ರಕ್ಷಿಸಲು ಪ್ರಾರಂಭಿಸಿ", "landing.hero.ctaSecondary": "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ",
  "landing.features.title": "AI-ಚಾಲಿತ ರಕ್ಷಣೆ", "landing.features.subtitle": "ಪ್ರತಿ ಭಾರತೀಯ ಕುಟುಂಬಕ್ಕೆ ರಿಯಲ್-ಟೈಮ್ ಬೆದರಿಕೆ ಪತ್ತೆ", "landing.features.scam.title": "ಸ್ಕ್ಯಾಮ್ & ಫಿಶಿಂಗ್ ಪತ್ತೆ", "landing.features.scam.desc": "AI SMS, ಇಮೇಲ್‌ಗಳು, ಲಿಂಕ್‌ಗಳು & QR ಕೋಡ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.", "landing.features.child.title": "ಮಕ್ಕಳ ಸುರಕ್ಷತೆ AI", "landing.features.child.desc": "ಆನ್‌ಲೈನ್ ಗ್ರೂಮಿಂಗ್, ಬೇಟೆಗಾರ ನಡವಳಿಕೆ & ಹಾನಿಕಾರಕ ವಿಷಯವನ್ನು ಪತ್ತೆಹಚ್ಚುತ್ತದೆ.", "landing.features.elderly.title": "ಹಿರಿಯರ ಸುರಕ್ಷತಾ ಮೋಡ್", "landing.features.elderly.desc": "ಒಂದು-ಟ್ಯಾಪ್ 'ಇದು ಸ್ಕ್ಯಾಮ್ ಆ?' ದೊಡ್ಡ ಅಕ್ಷರ, ಸ್ಪಷ್ಟ ಫಲಿತಾಂಶಗಳು & ಧ್ವನಿ ಎಚ್ಚರಿಕೆಗಳೊಂದಿಗೆ.", "landing.features.women.title": "ಮಹಿಳಾ ಸುರಕ್ಷತೆ", "landing.features.women.desc": "ನಕಲಿ ಪ್ರೊಫೈಲ್‌ಗಳು, ಸೆಕ್ಸ್‌ಟಾರ್ಶನ್ & ಬ್ಲ್ಯಾಕ್‌ಮೇಲ್ ಪತ್ತೆ.", "landing.features.dashboard.title": "ಪೋಷಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", "landing.features.dashboard.desc": "ತಡೆಹಿಡಿದ ಬೆದರಿಕೆಗಳು, ಅಪಾಯ ಅಂಕಗಳು & ಕುಟುಂಬ ಸುರಕ್ಷತಾ ಪ್ರವೃತ್ತಿಗಳ ದೃಶ್ಯ ಅವಲೋಕನ.", "landing.features.privacy.title": "ಗೌಪ್ಯತೆ-ಮೊದಲ AI", "landing.features.privacy.desc": "ಶಾಶ್ವತ ಸಂದೇಶ ಸಂಗ್ರಹಣೆ ಇಲ್ಲ. ಪಾರದರ್ಶಕ AI ವಿವರಣೆಗಳು. ನಿಮ್ಮ ಡೇಟಾ ನಿಮ್ಮದು.",
  "landing.impact.title": "ಭಾರತವನ್ನು ಸುರಕ್ಷಿತವಾಗಿಸುವುದು", "landing.impact.threats": "ಬೆದರಿಕೆಗಳು ತಡೆಯಲಾಗಿದೆ", "landing.impact.scams": "ಸ್ಕ್ಯಾಮ್‌ಗಳು ಪತ್ತೆಯಾಗಿವೆ", "landing.impact.children": "ಮಕ್ಕಳು ರಕ್ಷಿಸಲಾಗಿದೆ", "landing.impact.saved": "ಉಳಿಸಲಾಗಿದೆ (₹)", "landing.modes.title": "ಎಲ್ಲರಿಗೂ ನಿರ್ಮಿಸಲಾಗಿದೆ", "landing.modes.subtitle": "CyberShield ನಿಮ್ಮ ಅಗತ್ಯಗಳಿಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ", "landing.cta.title": "ಇಂದೇ ನಿಮ್ಮ ಕುಟುಂಬವನ್ನು ರಕ್ಷಿಸಿ", "landing.cta.subtitle": "AI-ಚಾಲಿತ ಡಿಜಿಟಲ್ ಸುರಕ್ಷತೆಯನ್ನು ಬಳಸುತ್ತಿರುವ ಸಾವಿರಾರು ಭಾರತೀಯ ಕುಟುಂಬಗಳೊಂದಿಗೆ ಸೇರಿಕೊಳ್ಳಿ.", "landing.cta.button": "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
  "auth.login.title": "ಮರಳಿ ಸ್ವಾಗತ", "auth.login.subtitle": "ನಿಮ್ಮ CyberShield ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ", "auth.signup.title": "ಖಾತೆ ರಚಿಸಿ", "auth.signup.subtitle": "ಇಂದೇ ನಿಮ್ಮ ಕುಟುಂಬವನ್ನು ರಕ್ಷಿಸಲು ಪ್ರಾರಂಭಿಸಿ", "auth.email": "ಇಮೇಲ್", "auth.password": "ಪಾಸ್‌ವರ್ಡ್", "auth.name": "ಪೂರ್ಣ ಹೆಸರು", "auth.loginButton": "ಸೈನ್ ಇನ್", "auth.signupButton": "ಖಾತೆ ರಚಿಸಿ", "auth.noAccount": "ಖಾತೆ ಇಲ್ಲವೇ?", "auth.hasAccount": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?", "auth.checkEmail": "ಪರಿಶೀಲನೆ ಲಿಂಕ್‌ಗಾಗಿ ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.",
  "onboarding.title": "ನೀವು CyberShield ಹೇಗೆ ಬಳಸುತ್ತೀರಿ?", "onboarding.subtitle": "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡುತ್ತೇವೆ", "onboarding.parent": "ಪೋಷಕರು", "onboarding.parentDesc": "ಕುಟುಂಬ ಸುರಕ್ಷತೆ & ಬೆದರಿಕೆ ಮೇಲ್ವಿಚಾರಣೆ", "onboarding.child": "ಯುವ ಬಳಕೆದಾರ", "onboarding.childDesc": "ಸುರಕ್ಷಿತ ಬ್ರೌಸಿಂಗ್ & ಯೋಗಕ್ಷೇಮ", "onboarding.elderly": "ಹಿರಿಯ ನಾಗರಿಕ", "onboarding.elderlyDesc": "ಸರಳ ಸ್ಕ್ಯಾಮ್ ಪತ್ತೆ", "onboarding.continue": "ಮುಂದುವರಿಸಿ",
  "scanner.title": "ಸ್ಕ್ಯಾಮ್ ಸ್ಕ್ಯಾನರ್", "scanner.subtitle": "AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಅನುಮಾನಾಸ್ಪದ ಸಂದೇಶಗಳು ಅಥವಾ URLಗಳನ್ನು ಅಂಟಿಸಿ", "scanner.textTab": "ಪಠ್ಯ ಸಂದೇಶ", "scanner.urlTab": "URL / ಲಿಂಕ್", "scanner.textPlaceholder": "ಅನುಮಾನಾಸ್ಪದ SMS, WhatsApp ಸಂದೇಶ, ಅಥವಾ ಇಮೇಲ್ ಪಠ್ಯವನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ...", "scanner.urlPlaceholder": "https://suspicious-link.com", "scanner.scanButton": "ಈಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ", "scanner.scanning": "ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...", "scanner.result.safe": "ಸುರಕ್ಷಿತ", "scanner.result.suspicious": "ಅನುಮಾನಾಸ್ಪದ", "scanner.result.dangerous": "ಅಪಾಯಕಾರಿ", "scanner.elderly.title": "ಇದು ಸ್ಕ್ಯಾಮ್ ಆ?", "scanner.elderly.subtitle": "ಕೆಳಗೆ ಸಂದೇಶ ಅಂಟಿಸಿ ಮತ್ತು ದೊಡ್ಡ ಬಟನ್ ಒತ್ತಿ", "scanner.elderly.button": "ಈಗ ಪರಿಶೀಲಿಸಿ",
  "dashboard.title": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", "dashboard.threats": "ಬೆದರಿಕೆಗಳು ತಡೆಯಲಾಗಿದೆ", "dashboard.scams": "ಸ್ಕ್ಯಾಮ್‌ಗಳು ಪತ್ತೆಯಾಗಿವೆ", "dashboard.riskScore": "ಕುಟುಂಬ ಅಪಾಯ ಅಂಕ", "dashboard.recentAlerts": "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು", "dashboard.scanHistory": "ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ", "dashboard.noData": "ಇನ್ನೂ ಡೇಟಾ ಇಲ್ಲ. ಒಳನೋಟಗಳನ್ನು ನೋಡಲು ಸ್ಕ್ಯಾನಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ.",
  "emergency.sos.title": "ತುರ್ತು SOS", "emergency.sos.subtitle": "ಪರಿಶೀಲಿಸಿದ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿಗಳು & ತುರ್ತು ಸಹಾಯಕ್ಕೆ ತಕ್ಷಣ ಪ್ರವೇಶ", "emergency.sos.confirm": "ನೀವು ಅಪಾಯದಲ್ಲಿದ್ದೀರಾ?", "emergency.sos.yes": "ಹೌದು, ನನಗೆ ಸಹಾಯ ಬೇಕು", "emergency.sos.no": "ಇಲ್ಲ, ನಾನು ಸುರಕ್ಷಿತವಾಗಿದ್ದೇನೆ",
  "common.loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...", "common.error": "ಏನೋ ತಪ್ಪಾಯಿತು", "common.darkMode": "ಡಾರ್ಕ್ ಮೋಡ್", "common.lightMode": "ಲೈಟ್ ಮೋಡ್", "common.language": "ಭಾಷೆ",
} as const;
