export const ml = {
  "nav.home": "ഹോം", "nav.scanner": "തട്ടിപ്പ് സ്കാനർ", "nav.childSafety": "കുട്ടികളുടെ സുരക്ഷ", "nav.dashboard": "ഡാഷ്ബോർഡ്", "nav.alerts": "അലേർട്ടുകൾ", "nav.family": "കുടുംബം", "nav.wellbeing": "ക്ഷേമം", "nav.womenSafety": "വനിതാ സുരക്ഷ", "nav.impact": "സ്വാധീനം", "nav.about": "ഞങ്ങളെക്കുറിച്ച്", "nav.settings": "ക്രമീകരണങ്ങൾ", "nav.login": "ലോഗിൻ", "nav.signup": "സൈൻ അപ്പ്", "nav.logout": "ലോഗൗട്ട്", "nav.emergency": "🆘 അടിയന്തരം",
  "landing.hero.title": "ഇന്ത്യയുടെ AI രക്ഷകൻ", "landing.hero.titleHighlight": "ഡിജിറ്റൽ സുരക്ഷ", "landing.hero.subtitle": "കുട്ടികൾ, കുടുംബങ്ങൾ & മുതിർന്നവരെ സൈബർ തട്ടിപ്പ്, സ്കാം, ഓൺലൈൻ ഭീഷണികളിൽ നിന്ന് സംരക്ഷിക്കുന്നു — AI ശക്തിയിൽ, ഇന്ത്യയ്ക്കായി നിർമ്മിച്ചത്.", "landing.hero.cta": "നിങ്ങളുടെ കുടുംബത്തെ സംരക്ഷിക്കാൻ ആരംഭിക്കുക", "landing.hero.ctaSecondary": "കൂടുതൽ അറിയുക",
  "landing.features.title": "AI-പവർഡ് സംരക്ഷണം", "landing.features.subtitle": "ഓരോ ഇന്ത്യൻ കുടുംബത്തിനും തത്സമയ ഭീഷണി കണ്ടെത്തൽ", "landing.features.scam.title": "തട്ടിപ്പ് & ഫിഷിംഗ് കണ്ടെത്തൽ", "landing.features.scam.desc": "AI SMS, ഇമെയിലുകൾ, ലിങ്കുകൾ & QR കോഡുകൾ വിശകലനം ചെയ്യുന്നു.", "landing.features.child.title": "കുട്ടികളുടെ സുരക്ഷ AI", "landing.features.child.desc": "ഓൺലൈൻ ഗ്രൂമിംഗ്, വേട്ടക്കാരൻ സ്വഭാവം & ദോഷകരമായ ഉള്ളടക്കം കണ്ടെത്തുന്നു.", "landing.features.elderly.title": "മുതിർന്നവരുടെ സുരക്ഷാ മോഡ്", "landing.features.elderly.desc": "ഒരു-ടാപ്പ് 'ഇത് തട്ടിപ്പാണോ?' വലിയ ടെക്സ്റ്റ്, വ്യക്തമായ ഫലങ്ങൾ & വോയ്‌സ് അലേർട്ടുകളോടെ.", "landing.features.women.title": "വനിതാ സുരക്ഷ", "landing.features.women.desc": "വ്യാജ പ്രൊഫൈലുകൾ, സെക്‌സ്‌ടോർഷൻ & ബ്ലാക്ക്‌മെയിൽ കണ്ടെത്തൽ.", "landing.features.dashboard.title": "രക്ഷകർതൃ ഡാഷ്ബോർഡ്", "landing.features.dashboard.desc": "തടഞ്ഞ ഭീഷണികൾ, റിസ്ക് സ്കോറുകൾ & കുടുംബ സുരക്ഷാ ട്രെൻഡുകളുടെ വിഷ്വൽ അവലോകനം.", "landing.features.privacy.title": "സ്വകാര്യത-ഫസ്റ്റ് AI", "landing.features.privacy.desc": "സ്ഥിരമായ സന്ദേശ സംഭരണം ഇല്ല. സുതാര്യ AI വിശദീകരണങ്ങൾ. നിങ്ങളുടെ ഡാറ്റ നിങ്ങളുടേത്.",
  "landing.impact.title": "ഇന്ത്യയെ സുരക്ഷിതമാക്കുന്നു", "landing.impact.threats": "ഭീഷണികൾ തടഞ്ഞു", "landing.impact.scams": "തട്ടിപ്പുകൾ കണ്ടെത്തി", "landing.impact.children": "കുട്ടികൾ സംരക്ഷിതം", "landing.impact.saved": "സേവ് ചെയ്തു (₹)", "landing.modes.title": "എല്ലാവർക്കുമായി നിർമ്മിച്ചത്", "landing.modes.subtitle": "CyberShield നിങ്ങളുടെ ആവശ്യങ്ങൾക്കനുസരിച്ച് മാറുന്നു", "landing.cta.title": "ഇന്ന് തന്നെ നിങ്ങളുടെ കുടുംബത്തെ സംരക്ഷിക്കുക", "landing.cta.subtitle": "AI-പവർഡ് ഡിജിറ്റൽ സുരക്ഷ ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് ഇന്ത്യൻ കുടുംബങ്ങളോടൊപ്പം ചേരുക.", "landing.cta.button": "സൗജന്യമായി ആരംഭിക്കുക",
  "auth.login.title": "തിരികെ സ്വാഗതം", "auth.login.subtitle": "നിങ്ങളുടെ CyberShield അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക", "auth.signup.title": "അക്കൗണ്ട് സൃഷ്ടിക്കുക", "auth.signup.subtitle": "ഇന്ന് തന്നെ നിങ്ങളുടെ കുടുംബത്തെ സംരക്ഷിക്കാൻ ആരംഭിക്കുക", "auth.email": "ഇമെയിൽ", "auth.password": "പാസ്‌വേഡ്", "auth.name": "മുഴുവൻ പേര്", "auth.loginButton": "സൈൻ ഇൻ", "auth.signupButton": "അക്കൗണ്ട് സൃഷ്ടിക്കുക", "auth.noAccount": "അക്കൗണ്ട് ഇല്ലേ?", "auth.hasAccount": "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?", "auth.checkEmail": "സ്ഥിരീകരണ ലിങ്കിനായി നിങ്ങളുടെ ഇമെയിൽ പരിശോധിക്കുക.",
  "onboarding.title": "നിങ്ങൾ CyberShield എങ്ങനെ ഉപയോഗിക്കും?", "onboarding.subtitle": "നിങ്ങളുടെ അനുഭവം ഇഷ്ടാനുസൃതമാക്കും", "onboarding.parent": "രക്ഷകർത്താവ്", "onboarding.parentDesc": "കുടുംബ സുരക്ഷ & ഭീഷണി നിരീക്ഷണം", "onboarding.child": "യുവ ഉപയോക്താവ്", "onboarding.childDesc": "സുരക്ഷിത ബ്രൗസിംഗ് & ക്ഷേമം", "onboarding.elderly": "മുതിർന്ന പൗരൻ", "onboarding.elderlyDesc": "ലളിതമായ തട്ടിപ്പ് കണ്ടെത്തൽ", "onboarding.continue": "തുടരുക",
  "scanner.title": "തട്ടിപ്പ് സ്കാനർ", "scanner.subtitle": "AI വിശകലനത്തിനായി സംശയാസ്പദ സന്ദേശങ്ങൾ അല്ലെങ്കിൽ URLകൾ ഒട്ടിക്കുക", "scanner.textTab": "ടെക്സ്റ്റ് സന്ദേശം", "scanner.urlTab": "URL / ലിങ്ക്", "scanner.textPlaceholder": "സംശയാസ്പദ SMS, WhatsApp സന്ദേശം, അല്ലെങ്കിൽ ഇമെയിൽ ടെക്സ്റ്റ് ഇവിടെ ഒട്ടിക്കുക...", "scanner.urlPlaceholder": "https://suspicious-link.com", "scanner.scanButton": "ഇപ്പോൾ സ്കാൻ ചെയ്യുക", "scanner.scanning": "വിശകലനം ചെയ്യുന്നു...", "scanner.result.safe": "സുരക്ഷിതം", "scanner.result.suspicious": "സംശയാസ്പദം", "scanner.result.dangerous": "അപകടകരം", "scanner.elderly.title": "ഇത് തട്ടിപ്പാണോ?", "scanner.elderly.subtitle": "താഴെ സന്ദേശം ഒട്ടിച്ച് വലിയ ബട്ടൺ അമർത്തുക", "scanner.elderly.button": "ഇപ്പോൾ പരിശോധിക്കുക",
  "dashboard.title": "ഡാഷ്ബോർഡ്", "dashboard.threats": "ഭീഷണികൾ തടഞ്ഞു", "dashboard.scams": "തട്ടിപ്പുകൾ കണ്ടെത്തി", "dashboard.riskScore": "കുടുംബ റിസ്ക് സ്കോർ", "dashboard.recentAlerts": "സമീപകാല അലേർട്ടുകൾ", "dashboard.scanHistory": "സ്കാൻ ചരിത്രം", "dashboard.noData": "ഇതുവരെ ഡാറ്റ ഇല്ല. ഇൻസൈറ്റുകൾ കാണാൻ സ്കാനിംഗ് ആരംഭിക്കുക.",
  "emergency.sos.title": "അടിയന്തര SOS", "emergency.sos.subtitle": "പരിശോധിച്ച ദേശീയ ഹെൽപ്‌ലൈനുകളും അടിയന്തര സഹായവും ഉടനടി ആക്‌സസ്", "emergency.sos.confirm": "നിങ്ങൾ അപകടത്തിലാണോ?", "emergency.sos.yes": "അതെ, എനിക്ക് സഹായം വേണം", "emergency.sos.no": "അല്ല, ഞാൻ സുരക്ഷിതമാണ്",
  "common.loading": "ലോഡ് ചെയ്യുന്നു...", "common.error": "എന്തോ തെറ്റ് സംഭവിച്ചു", "common.darkMode": "ഡാർക്ക് മോഡ്", "common.lightMode": "ലൈറ്റ് മോഡ്", "common.language": "ഭാഷ",
} as const;
