export const or_ = {
  "nav.home": "ହୋମ", "nav.scanner": "ସ୍କାମ ସ୍କାନର", "nav.childSafety": "ଶିଶୁ ସୁରକ୍ଷା", "nav.dashboard": "ଡ୍ୟାସବୋର୍ଡ", "nav.alerts": "ସତର୍କତା", "nav.family": "ପରିବାର", "nav.wellbeing": "ସୁସ୍ଥତା", "nav.womenSafety": "ମହିଳା ସୁରକ୍ଷା", "nav.impact": "ପ୍ରଭାବ", "nav.about": "ଆମ ବିଷୟରେ", "nav.settings": "ସେଟିଂସ", "nav.login": "ଲଗଇନ", "nav.signup": "ସାଇନ ଅପ", "nav.logout": "ଲଗଆଉଟ", "nav.emergency": "🆘 ଜରୁରୀ",
  "landing.hero.title": "ଭାରତର AI ରକ୍ଷକ", "landing.hero.titleHighlight": "ଡିଜିଟାଲ ସୁରକ୍ଷା", "landing.hero.subtitle": "ଶିଶୁ, ପରିବାର ଓ ବୟସ୍କମାନଙ୍କୁ ସାଇବର ଠକେଇ, ସ୍କାମ ଓ ଅନଲାଇନ ବିପଦରୁ ସୁରକ୍ଷା — AI ଦ୍ୱାରା, ଭାରତ ପାଇଁ ନିର୍ମିତ.", "landing.hero.cta": "ଆପଣଙ୍କ ପରିବାରକୁ ସୁରକ୍ଷିତ କରିବା ଆରମ୍ଭ କରନ୍ତୁ", "landing.hero.ctaSecondary": "ଅଧିକ ଜାଣନ୍ତୁ",
  "landing.features.title": "AI-ଚାଳିତ ସୁରକ୍ଷା", "landing.features.subtitle": "ପ୍ରତ୍ୟେକ ଭାରତୀୟ ପରିବାର ପାଇଁ ରିଅଲ-ଟାଇମ ବିପଦ ଚିହ୍ନଟ", "landing.features.scam.title": "ସ୍କାମ ଓ ଫିସିଂ ଚିହ୍ନଟ", "landing.features.scam.desc": "AI SMS, ଇମେଲ, ଲିଙ୍କ ଓ QR କୋଡ ବିଶ୍ଳେଷଣ କରେ.", "landing.features.child.title": "ଶିଶୁ ସୁରକ୍ଷା AI", "landing.features.child.desc": "ଅନଲାଇନ ଗ୍ରୁମିଂ, ଶିକାରୀ ଆଚରଣ ଓ କ୍ଷତିକାରକ ବିଷୟବସ୍ତୁ ଚିହ୍ନଟ କରେ.", "landing.features.elderly.title": "ବୟସ୍କ ସୁରକ୍ଷା ମୋଡ", "landing.features.elderly.desc": "ଗୋଟିଏ-ଟ୍ୟାପ 'ଏହା ସ୍କାମ କି?' ବଡ ଅକ୍ଷର, ସ୍ପଷ୍ଟ ଫଳାଫଳ ଓ ସ୍ୱର ସତର୍କତା ସହିତ.", "landing.features.women.title": "ମହିଳା ସୁରକ୍ଷା", "landing.features.women.desc": "ନକଲି ପ୍ରୋଫାଇଲ, ସେକ୍ସଟର୍ସନ ଓ ବ୍ଲାକମେଲ ଚିହ୍ନଟ.", "landing.features.dashboard.title": "ଅଭିଭାବକ ଡ୍ୟାସବୋର୍ଡ", "landing.features.dashboard.desc": "ରୋକାଯାଇଥିବା ବିପଦ, ଜୋଖିମ ସ୍କୋର ଓ ପରିବାର ସୁରକ୍ଷା ଟ୍ରେଣ୍ଡର ଦୃଶ୍ୟ ଅବଲୋକନ.", "landing.features.privacy.title": "ଗୋପନୀୟତା-ପ୍ରଥମ AI", "landing.features.privacy.desc": "ସ୍ଥାୟୀ ସନ୍ଦେଶ ସଂରକ୍ଷଣ ନାହିଁ. ସ୍ୱଚ୍ଛ AI ବ୍ୟାଖ୍ୟା. ଆପଣଙ୍କ ଡାଟା ଆପଣଙ୍କର.",
  "landing.impact.title": "ଭାରତକୁ ସୁରକ୍ଷିତ କରିବା", "landing.impact.threats": "ବିପଦ ରୋକାଗଲା", "landing.impact.scams": "ସ୍କାମ ଚିହ୍ନଟ ହେଲା", "landing.impact.children": "ଶିଶୁ ସୁରକ୍ଷିତ", "landing.impact.saved": "ସଞ୍ଚୟ (₹)", "landing.modes.title": "ସମସ୍ତଙ୍କ ପାଇଁ ନିର୍ମିତ", "landing.modes.subtitle": "CyberShield ଆପଣଙ୍କ ଆବଶ୍ୟକତା ଅନୁସାରେ ଅନୁକୂଳ ହୁଏ", "landing.cta.title": "ଆଜି ହିଁ ଆପଣଙ୍କ ପରିବାରକୁ ସୁରକ୍ଷିତ କରନ୍ତୁ", "landing.cta.subtitle": "AI-ଚାଳିତ ଡିଜିଟାଲ ସୁରକ୍ଷା ବ୍ୟବହାର କରୁଥିବା ହଜାରେ ଭାରତୀୟ ପରିବାର ସହ ଯୋଗ ଦିଅନ୍ତୁ.", "landing.cta.button": "ମାଗଣାରେ ଆରମ୍ଭ କରନ୍ତୁ",
  "auth.login.title": "ପୁଣି ସ୍ୱାଗତ", "auth.login.subtitle": "ଆପଣଙ୍କ CyberShield ଖାତାରେ ସାଇନ ଇନ କରନ୍ତୁ", "auth.signup.title": "ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ", "auth.signup.subtitle": "ଆଜି ହିଁ ଆପଣଙ୍କ ପରିବାରକୁ ସୁରକ୍ଷିତ କରିବା ଆରମ୍ଭ କରନ୍ତୁ", "auth.email": "ଇମେଲ", "auth.password": "ପାସୱାର୍ଡ", "auth.name": "ପୂରା ନାମ", "auth.loginButton": "ସାଇନ ଇନ", "auth.signupButton": "ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ", "auth.noAccount": "ଖାତା ନାହିଁ?", "auth.hasAccount": "ଆଗରୁ ଖାତା ଅଛି?", "auth.checkEmail": "ଯାଞ୍ଚ ଲିଙ୍କ ପାଇଁ ଆପଣଙ୍କ ଇମେଲ ଚେକ କରନ୍ତୁ.",
  "onboarding.title": "ଆପଣ CyberShield କିପରି ବ୍ୟବହାର କରିବେ?", "onboarding.subtitle": "ଆମେ ଆପଣଙ୍କ ଅନୁଭବ କଷ୍ଟମାଇଜ କରିବୁ", "onboarding.parent": "ଅଭିଭାବକ", "onboarding.parentDesc": "ପରିବାର ସୁରକ୍ଷା ଓ ବିପଦ ନିରୀକ୍ଷଣ", "onboarding.child": "ଯୁବ ବ୍ୟବହାରକାରୀ", "onboarding.childDesc": "ସୁରକ୍ଷିତ ବ୍ରାଉଜିଂ ଓ ସୁସ୍ଥତା", "onboarding.elderly": "ବରିଷ୍ଠ ନାଗରିକ", "onboarding.elderlyDesc": "ସରଳ ସ୍କାମ ଚିହ୍ନଟ", "onboarding.continue": "ଜାରି ରଖନ୍ତୁ",
  "scanner.title": "ସ୍କାମ ସ୍କାନର", "scanner.subtitle": "AI ବିଶ୍ଳେଷଣ ପାଇଁ ସନ୍ଦିଗ୍ଧ ସନ୍ଦେଶ ବା URL ପେଷ୍ଟ କରନ୍ତୁ", "scanner.textTab": "ଟେକ୍ସଟ ସନ୍ଦେଶ", "scanner.urlTab": "URL / ଲିଙ୍କ", "scanner.textPlaceholder": "ସନ୍ଦିଗ୍ଧ SMS, WhatsApp ସନ୍ଦେଶ, ବା ଇମେଲ ଟେକ୍ସଟ ଏଠାରେ ପେଷ୍ଟ କରନ୍ତୁ...", "scanner.urlPlaceholder": "https://suspicious-link.com", "scanner.scanButton": "ବର୍ତ୍ତମାନ ସ୍କାନ କରନ୍ତୁ", "scanner.scanning": "ବିଶ୍ଳେଷଣ ହେଉଛି...", "scanner.result.safe": "ସୁରକ୍ଷିତ", "scanner.result.suspicious": "ସନ୍ଦିଗ୍ଧ", "scanner.result.dangerous": "ବିପଜ୍ଜନକ", "scanner.elderly.title": "ଏହା ସ୍କାମ କି?", "scanner.elderly.subtitle": "ତଳେ ସନ୍ଦେଶ ପେଷ୍ଟ କରନ୍ତୁ ଓ ବଡ ବଟନ ଦବାନ୍ତୁ", "scanner.elderly.button": "ବର୍ତ୍ତମାନ ଯାଞ୍ଚ କରନ୍ତୁ",
  "dashboard.title": "ଡ୍ୟାସବୋର୍ଡ", "dashboard.threats": "ବିପଦ ରୋକାଗଲା", "dashboard.scams": "ସ୍କାମ ଚିହ୍ନଟ ହେଲା", "dashboard.riskScore": "ପରିବାର ଜୋଖିମ ସ୍କୋର", "dashboard.recentAlerts": "ସାମ୍ପ୍ରତିକ ସତର୍କତା", "dashboard.scanHistory": "ସ୍କାନ ଇତିହାସ", "dashboard.noData": "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଡାଟା ନାହିଁ. ଇନସାଇଟ ଦେଖିବାକୁ ସ୍କାନିଂ ଆରମ୍ଭ କରନ୍ତୁ.",
  "emergency.sos.title": "ଜରୁରୀ SOS", "emergency.sos.subtitle": "ଯାଞ୍ଚ ହୋଇଥିବା ଜାତୀୟ ହେଲ୍ପଲାଇନ ଓ ଜରୁରୀ ସହାୟତାକୁ ତୁରନ୍ତ ପ୍ରବେଶ", "emergency.sos.confirm": "ଆପଣ ବିପଦରେ ଅଛନ୍ତି କି?", "emergency.sos.yes": "ହଁ, ମୋତେ ସାହାଯ୍ୟ ଦରକାର", "emergency.sos.no": "ନା, ମୁଁ ସୁରକ୍ଷିତ",
  "common.loading": "ଲୋଡ ହେଉଛି...", "common.error": "କିଛି ଭୁଲ ହେଲା", "common.darkMode": "ଡାର୍କ ମୋଡ", "common.lightMode": "ଲାଇଟ ମୋଡ", "common.language": "ଭାଷା",
} as const;
