export const pa = {
  "nav.home": "ਹੋਮ", "nav.scanner": "ਸਕੈਮ ਸਕੈਨਰ", "nav.childSafety": "ਬੱਚਿਆਂ ਦੀ ਸੁਰੱਖਿਆ", "nav.dashboard": "ਡੈਸ਼ਬੋਰਡ", "nav.alerts": "ਚੇਤਾਵਨੀਆਂ", "nav.family": "ਪਰਿਵਾਰ", "nav.wellbeing": "ਤੰਦਰੁਸਤੀ", "nav.womenSafety": "ਔਰਤਾਂ ਦੀ ਸੁਰੱਖਿਆ", "nav.impact": "ਪ੍ਰਭਾਵ", "nav.about": "ਸਾਡੇ ਬਾਰੇ", "nav.settings": "ਸੈਟਿੰਗਾਂ", "nav.login": "ਲੌਗਇਨ", "nav.signup": "ਸਾਈਨ ਅੱਪ", "nav.logout": "ਲੌਗਆਊਟ", "nav.emergency": "🆘 ਐਮਰਜੈਂਸੀ",
  "landing.hero.title": "ਭਾਰਤ ਦਾ AI ਰੱਖਿਅਕ", "landing.hero.titleHighlight": "ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ", "landing.hero.subtitle": "ਬੱਚਿਆਂ, ਪਰਿਵਾਰਾਂ ਅਤੇ ਬਜ਼ੁਰਗਾਂ ਨੂੰ ਸਾਈਬਰ ਧੋਖਾਧੜੀ, ਸਕੈਮ ਅਤੇ ਔਨਲਾਈਨ ਧਮਕੀਆਂ ਤੋਂ ਸੁਰੱਖਿਆ — AI ਦੁਆਰਾ, ਭਾਰਤ ਲਈ ਬਣਾਇਆ.", "landing.hero.cta": "ਆਪਣੇ ਪਰਿਵਾਰ ਦੀ ਸੁਰੱਖਿਆ ਸ਼ੁਰੂ ਕਰੋ", "landing.hero.ctaSecondary": "ਹੋਰ ਜਾਣੋ",
  "landing.features.title": "AI-ਸੰਚਾਲਿਤ ਸੁਰੱਖਿਆ", "landing.features.subtitle": "ਹਰ ਭਾਰਤੀ ਪਰਿਵਾਰ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਧਮਕੀ ਖੋਜ", "landing.features.scam.title": "ਸਕੈਮ ਅਤੇ ਫਿਸ਼ਿੰਗ ਖੋਜ", "landing.features.scam.desc": "AI SMS, ਈਮੇਲਾਂ, ਲਿੰਕ ਅਤੇ QR ਕੋਡ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦਾ ਹੈ.", "landing.features.child.title": "ਬੱਚਿਆਂ ਦੀ ਸੁਰੱਖਿਆ AI", "landing.features.child.desc": "ਔਨਲਾਈਨ ਗਰੂਮਿੰਗ, ਸ਼ਿਕਾਰੀ ਵਿਵਹਾਰ ਅਤੇ ਨੁਕਸਾਨਦੇਹ ਸਮੱਗਰੀ ਖੋਜਦਾ ਹੈ.", "landing.features.elderly.title": "ਬਜ਼ੁਰਗ ਸੁਰੱਖਿਆ ਮੋਡ", "landing.features.elderly.desc": "ਇੱਕ-ਟੈਪ 'ਕੀ ਇਹ ਸਕੈਮ ਹੈ?' ਵੱਡੇ ਅੱਖਰ, ਸਪਸ਼ਟ ਨਤੀਜੇ ਅਤੇ ਆਵਾਜ਼ ਚੇਤਾਵਨੀਆਂ ਨਾਲ.", "landing.features.women.title": "ਔਰਤਾਂ ਦੀ ਸੁਰੱਖਿਆ", "landing.features.women.desc": "ਨਕਲੀ ਪ੍ਰੋਫਾਈਲ, ਸੈਕਸਟੋਰਸ਼ਨ ਅਤੇ ਬਲੈਕਮੇਲ ਖੋਜ.", "landing.features.dashboard.title": "ਮਾਪਿਆਂ ਦਾ ਡੈਸ਼ਬੋਰਡ", "landing.features.dashboard.desc": "ਰੋਕੀਆਂ ਧਮਕੀਆਂ, ਜੋਖਮ ਸਕੋਰ ਅਤੇ ਪਰਿਵਾਰ ਸੁਰੱਖਿਆ ਰੁਝਾਨਾਂ ਦਾ ਦ੍ਰਿਸ਼ ਸੰਖੇਪ.", "landing.features.privacy.title": "ਗੋਪਨੀਯਤਾ-ਪਹਿਲਾ AI", "landing.features.privacy.desc": "ਕੋਈ ਸਥਾਈ ਸੁਨੇਹਾ ਸਟੋਰੇਜ ਨਹੀਂ. ਪਾਰਦਰਸ਼ੀ AI ਸਪਸ਼ਟੀਕਰਨ. ਤੁਹਾਡਾ ਡੇਟਾ ਤੁਹਾਡਾ.",
  "landing.impact.title": "ਭਾਰਤ ਨੂੰ ਸੁਰੱਖਿਅਤ ਬਣਾਉਣਾ", "landing.impact.threats": "ਧਮਕੀਆਂ ਰੋਕੀਆਂ", "landing.impact.scams": "ਸਕੈਮ ਖੋਜੇ", "landing.impact.children": "ਬੱਚੇ ਸੁਰੱਖਿਅਤ", "landing.impact.saved": "ਬਚਾਏ (₹)", "landing.modes.title": "ਸਭ ਲਈ ਬਣਾਇਆ", "landing.modes.subtitle": "CyberShield ਤੁਹਾਡੀਆਂ ਲੋੜਾਂ ਅਨੁਸਾਰ ਢਲਦਾ ਹੈ", "landing.cta.title": "ਅੱਜ ਹੀ ਆਪਣੇ ਪਰਿਵਾਰ ਦੀ ਸੁਰੱਖਿਆ ਕਰੋ", "landing.cta.subtitle": "AI-ਸੰਚਾਲਿਤ ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ ਵਰਤਣ ਵਾਲੇ ਹਜ਼ਾਰਾਂ ਭਾਰਤੀ ਪਰਿਵਾਰਾਂ ਨਾਲ ਜੁੜੋ.", "landing.cta.button": "ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ",
  "auth.login.title": "ਵਾਪਸ ਸਵਾਗਤ ਹੈ", "auth.login.subtitle": "ਆਪਣੇ CyberShield ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ", "auth.signup.title": "ਖਾਤਾ ਬਣਾਓ", "auth.signup.subtitle": "ਅੱਜ ਹੀ ਆਪਣੇ ਪਰਿਵਾਰ ਦੀ ਸੁਰੱਖਿਆ ਸ਼ੁਰੂ ਕਰੋ", "auth.email": "ਈਮੇਲ", "auth.password": "ਪਾਸਵਰਡ", "auth.name": "ਪੂਰਾ ਨਾਮ", "auth.loginButton": "ਸਾਈਨ ਇਨ", "auth.signupButton": "ਖਾਤਾ ਬਣਾਓ", "auth.noAccount": "ਖਾਤਾ ਨਹੀਂ ਹੈ?", "auth.hasAccount": "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?", "auth.checkEmail": "ਤਸਦੀਕ ਲਿੰਕ ਲਈ ਆਪਣੀ ਈਮੇਲ ਚੈੱਕ ਕਰੋ.",
  "onboarding.title": "ਤੁਸੀਂ CyberShield ਕਿਵੇਂ ਵਰਤੋਗੇ?", "onboarding.subtitle": "ਅਸੀਂ ਤੁਹਾਡਾ ਅਨੁਭਵ ਕਸਟਮਾਈਜ਼ ਕਰਾਂਗੇ", "onboarding.parent": "ਮਾਪੇ", "onboarding.parentDesc": "ਪਰਿਵਾਰ ਸੁਰੱਖਿਆ ਅਤੇ ਧਮਕੀ ਨਿਗਰਾਨੀ", "onboarding.child": "ਨੌਜਵਾਨ ਵਰਤੋਂਕਾਰ", "onboarding.childDesc": "ਸੁਰੱਖਿਅਤ ਬ੍ਰਾਊਜ਼ਿੰਗ ਅਤੇ ਤੰਦਰੁਸਤੀ", "onboarding.elderly": "ਸੀਨੀਅਰ ਨਾਗਰਿਕ", "onboarding.elderlyDesc": "ਸਰਲ ਸਕੈਮ ਖੋਜ", "onboarding.continue": "ਜਾਰੀ ਰੱਖੋ",
  "scanner.title": "ਸਕੈਮ ਸਕੈਨਰ", "scanner.subtitle": "AI ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਸ਼ੱਕੀ ਸੁਨੇਹੇ ਜਾਂ URL ਪੇਸਟ ਕਰੋ", "scanner.textTab": "ਟੈਕਸਟ ਸੁਨੇਹਾ", "scanner.urlTab": "URL / ਲਿੰਕ", "scanner.textPlaceholder": "ਸ਼ੱਕੀ SMS, WhatsApp ਸੁਨੇਹਾ, ਜਾਂ ਈਮੇਲ ਟੈਕਸਟ ਇੱਥੇ ਪੇਸਟ ਕਰੋ...", "scanner.urlPlaceholder": "https://suspicious-link.com", "scanner.scanButton": "ਹੁਣੇ ਸਕੈਨ ਕਰੋ", "scanner.scanning": "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...", "scanner.result.safe": "ਸੁਰੱਖਿਅਤ", "scanner.result.suspicious": "ਸ਼ੱਕੀ", "scanner.result.dangerous": "ਖ਼ਤਰਨਾਕ", "scanner.elderly.title": "ਕੀ ਇਹ ਸਕੈਮ ਹੈ?", "scanner.elderly.subtitle": "ਹੇਠਾਂ ਸੁਨੇਹਾ ਪੇਸਟ ਕਰੋ ਅਤੇ ਵੱਡਾ ਬਟਨ ਦਬਾਓ", "scanner.elderly.button": "ਹੁਣੇ ਜਾਂਚ ਕਰੋ",
  "dashboard.title": "ਡੈਸ਼ਬੋਰਡ", "dashboard.threats": "ਧਮਕੀਆਂ ਰੋਕੀਆਂ", "dashboard.scams": "ਸਕੈਮ ਖੋਜੇ", "dashboard.riskScore": "ਪਰਿਵਾਰ ਜੋਖਮ ਸਕੋਰ", "dashboard.recentAlerts": "ਤਾਜ਼ਾ ਚੇਤਾਵਨੀਆਂ", "dashboard.scanHistory": "ਸਕੈਨ ਇਤਿਹਾਸ", "dashboard.noData": "ਅਜੇ ਕੋਈ ਡੇਟਾ ਨਹੀਂ. ਇਨਸਾਈਟ ਵੇਖਣ ਲਈ ਸਕੈਨਿੰਗ ਸ਼ੁਰੂ ਕਰੋ.",
  "emergency.sos.title": "ਐਮਰਜੈਂਸੀ SOS", "emergency.sos.subtitle": "ਤਸਦੀਕ ਕੀਤੀਆਂ ਰਾਸ਼ਟਰੀ ਹੈਲਪਲਾਈਨਾਂ ਅਤੇ ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ ਤੱਕ ਤੁਰੰਤ ਪਹੁੰਚ", "emergency.sos.confirm": "ਕੀ ਤੁਸੀਂ ਖ਼ਤਰੇ ਵਿੱਚ ਹੋ?", "emergency.sos.yes": "ਹਾਂ, ਮੈਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ", "emergency.sos.no": "ਨਹੀਂ, ਮੈਂ ਸੁਰੱਖਿਅਤ ਹਾਂ",
  "common.loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...", "common.error": "ਕੁਝ ਗ਼ਲਤ ਹੋ ਗਿਆ", "common.darkMode": "ਡਾਰਕ ਮੋਡ", "common.lightMode": "ਲਾਈਟ ਮੋਡ", "common.language": "ਭਾਸ਼ਾ",
} as const;
