export const ur = {
  "nav.home": "ہوم", "nav.scanner": "اسکیم سکینر", "nav.childSafety": "بچوں کی حفاظت", "nav.dashboard": "ڈیش بورڈ", "nav.alerts": "الرٹس", "nav.family": "خاندان", "nav.wellbeing": "فلاح", "nav.womenSafety": "خواتین کی حفاظت", "nav.impact": "اثر", "nav.about": "ہمارے بارے میں", "nav.settings": "ترتیبات", "nav.login": "لاگ ان", "nav.signup": "سائن اپ", "nav.logout": "لاگ آؤٹ", "nav.emergency": "🆘 ایمرجنسی",
  "landing.hero.title": "ہندوستان کا AI محافظ", "landing.hero.titleHighlight": "ڈیجیٹل تحفظ", "landing.hero.subtitle": "بچوں، خاندانوں اور بزرگوں کو سائبر فراڈ، اسکیم اور آن لائن خطرات سے تحفظ — AI کے ذریعے، ہندوستان کے لیے بنایا گیا۔", "landing.hero.cta": "اپنے خاندان کی حفاظت شروع کریں", "landing.hero.ctaSecondary": "مزید جانیں",
  "landing.features.title": "AI سے چلنے والا تحفظ", "landing.features.subtitle": "ہر ہندوستانی خاندان کے لیے ریئل ٹائم خطرے کی نشاندہی", "landing.features.scam.title": "اسکیم اور فشنگ کی نشاندہی", "landing.features.scam.desc": "AI SMS، ای میلز، لنکس اور QR کوڈز کا تجزیہ کرتا ہے۔", "landing.features.child.title": "بچوں کی حفاظت AI", "landing.features.child.desc": "آن لائن گرومنگ، شکاری رویے اور نقصان دہ مواد کا پتہ لگاتا ہے۔", "landing.features.elderly.title": "بزرگوں کا سیفٹی موڈ", "landing.features.elderly.desc": "ایک ٹیپ 'کیا یہ اسکیم ہے؟' بڑے متن، واضح نتائج اور آواز الرٹس کے ساتھ۔", "landing.features.women.title": "خواتین کی حفاظت", "landing.features.women.desc": "جعلی پروفائلز، سیکسٹارشن اور بلیک میل کی نشاندہی۔", "landing.features.dashboard.title": "والدین کا ڈیش بورڈ", "landing.features.dashboard.desc": "روکے گئے خطرات، رسک اسکورز اور خاندانی تحفظ کے رجحانات کا بصری جائزہ۔", "landing.features.privacy.title": "رازداری پہلے AI", "landing.features.privacy.desc": "کوئی مستقل پیغام ذخیرہ نہیں۔ شفاف AI وضاحتیں۔ آپ کا ڈیٹا آپ کا۔",
  "landing.impact.title": "ہندوستان کو محفوظ بنانا", "landing.impact.threats": "خطرات روکے گئے", "landing.impact.scams": "اسکیم پکڑے گئے", "landing.impact.children": "بچے محفوظ", "landing.impact.saved": "بچائے گئے (₹)", "landing.modes.title": "سب کے لیے بنایا گیا", "landing.modes.subtitle": "CyberShield آپ کی ضروریات کے مطابق ڈھلتا ہے", "landing.cta.title": "آج ہی اپنے خاندان کی حفاظت کریں", "landing.cta.subtitle": "AI سے چلنے والے ڈیجیٹل تحفظ کا استعمال کرنے والے ہزاروں ہندوستانی خاندانوں سے جڑیں۔", "landing.cta.button": "مفت شروع کریں",
  "auth.login.title": "واپسی پر خوش آمدید", "auth.login.subtitle": "اپنے CyberShield اکاؤنٹ میں سائن ان کریں", "auth.signup.title": "اکاؤنٹ بنائیں", "auth.signup.subtitle": "آج ہی اپنے خاندان کی حفاظت شروع کریں", "auth.email": "ای میل", "auth.password": "پاس ورڈ", "auth.name": "پورا نام", "auth.loginButton": "سائن ان", "auth.signupButton": "اکاؤنٹ بنائیں", "auth.noAccount": "اکاؤنٹ نہیں ہے؟", "auth.hasAccount": "پہلے سے اکاؤنٹ ہے؟", "auth.checkEmail": "تصدیقی لنک کے لیے اپنا ای میل چیک کریں۔",
  "onboarding.title": "آپ CyberShield کیسے استعمال کریں گے؟", "onboarding.subtitle": "ہم آپ کا تجربہ اپنی مرضی کے مطابق بنائیں گے", "onboarding.parent": "والدین", "onboarding.parentDesc": "خاندانی تحفظ اور خطرے کی نگرانی", "onboarding.child": "نوجوان صارف", "onboarding.childDesc": "محفوظ براؤزنگ اور فلاح", "onboarding.elderly": "بزرگ شہری", "onboarding.elderlyDesc": "آسان اسکیم کی نشاندہی", "onboarding.continue": "جاری رکھیں",
  "scanner.title": "اسکیم سکینر", "scanner.subtitle": "AI تجزیے کے لیے مشکوک پیغامات یا URL پیسٹ کریں", "scanner.textTab": "ٹیکسٹ پیغام", "scanner.urlTab": "URL / لنک", "scanner.textPlaceholder": "مشکوک SMS، WhatsApp پیغام، یا ای میل ٹیکسٹ یہاں پیسٹ کریں...", "scanner.urlPlaceholder": "https://suspicious-link.com", "scanner.scanButton": "ابھی سکین کریں", "scanner.scanning": "تجزیہ ہو رہا ہے...", "scanner.result.safe": "محفوظ", "scanner.result.suspicious": "مشکوک", "scanner.result.dangerous": "خطرناک", "scanner.elderly.title": "کیا یہ اسکیم ہے؟", "scanner.elderly.subtitle": "نیچے پیغام پیسٹ کریں اور بڑا بٹن دبائیں", "scanner.elderly.button": "ابھی جانچیں",
  "dashboard.title": "ڈیش بورڈ", "dashboard.threats": "خطرات روکے گئے", "dashboard.scams": "اسکیم پکڑے گئے", "dashboard.riskScore": "خاندانی رسک اسکور", "dashboard.recentAlerts": "حالیہ الرٹس", "dashboard.scanHistory": "سکین تاریخ", "dashboard.noData": "ابھی تک کوئی ڈیٹا نہیں۔ بصیرت دیکھنے کے لیے سکیننگ شروع کریں۔",
  "emergency.sos.title": "ایمرجنسی SOS", "emergency.sos.subtitle": "تصدیق شدہ قومی ہیلپ لائنز اور ایمرجنسی مدد تک فوری رسائی", "emergency.sos.confirm": "کیا آپ خطرے میں ہیں؟", "emergency.sos.yes": "ہاں، مجھے مدد چاہیے", "emergency.sos.no": "نہیں، میں محفوظ ہوں",
  "common.loading": "لوڈ ہو رہا ہے...", "common.error": "کچھ غلط ہو گیا", "common.darkMode": "ڈارک موڈ", "common.lightMode": "لائٹ موڈ", "common.language": "زبان",
} as const;
